name: Calcpy

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: Calcpy
        environment-file: environment.yml
        python-version: 3.10
        auto-activate-base: false

    - name: Verify environment
      run: conda list

    - name: Lint with flake8
      run: |
        conda install flake8 -y
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest -y
        pytest
